### ISSUE TITLE
API - AttributeError: 'tuple' object has no attribute 'info'

### ISSUE THREAD

**Issue by Dutch77** [Gourieff/sd-webui-reactor#102]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Using API from swagger `/reactor/image`

Payload
```
{
  "source_image": "...",
  "target_image": "....",
  "source_faces_index": [0],
  "face_index": [0]
}
```
This works with version `v0.4.0` and does not with current `main` branch.

### Steps to reproduce the problem

Try the API with simple image with face on current main branch.

### Sysinfo

```
[API](http://localhost:8080/docs)  •  [Github](https://github.com/AUTOMATIC1111/stable-diffusion-webui)  •  [Gradio](https://gradio.app/)  •  [Startup profile](http://localhost:8080/#)  •  [Reload UI](http://localhost:8080/)
version: [v1.6.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/5ef669de080814067961f28357256e8fe27544f4)  •  python: 3.10.13  •  torch: 2.0.1+cu117  •  xformers: 0.0.21  •  gradio: 3.41.2  •  checkpoint: [c35782bad8]
```

### Relevant console log

```Shell
app_1  | *** API error: POST: http://localhost:8080/reactor/image {'error': 'AttributeError', 'detail': '', 'body': '', 'errors': "'tuple' object has no attribute 'info'"}
app_1  |     Traceback (most recent call last):
app_1  |       File "/usr/local/lib/python3.10/dist-packages/anyio/streams/memory.py", line 98, in receive
app_1  |         return self.receive_nowait()
app_1  |       File "/usr/local/lib/python3.10/dist-packages/anyio/streams/memory.py", line 93, in receive_nowait
app_1  |         raise WouldBlock
app_1  |     anyio.WouldBlock
app_1  | 
app_1  |     During handling of the above exception, another exception occurred:
app_1  | 
app_1  |     Traceback (most recent call last):
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 78, in call_next
app_1  |         message = await recv_stream.receive()
app_1  |       File "/usr/local/lib/python3.10/dist-packages/anyio/streams/memory.py", line 118, in receive
app_1  |         raise EndOfStream
app_1  |     anyio.EndOfStream
app_1  | 
app_1  |     During handling of the above exception, another exception occurred:
app_1  | 
app_1  |     Traceback (most recent call last):
app_1  |       File "/workspace/stable-diffusion-webui/modules/api/api.py", line 187, in exception_handling
app_1  |         return await call_next(request)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 84, in call_next
app_1  |         raise app_exc
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 70, in coro
app_1  |         await self.app(scope, receive_or_disconnect, send_no_error)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 108, in __call__
app_1  |         response = await self.dispatch_func(request, call_next)
app_1  |       File "/workspace/stable-diffusion-webui/modules/api/api.py", line 151, in log_and_time
app_1  |         res: Response = await call_next(req)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 84, in call_next
app_1  |         raise app_exc
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/base.py", line 70, in coro
app_1  |         await self.app(scope, receive_or_disconnect, send_no_error)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 84, in __call__
app_1  |         await self.app(scope, receive, send)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 24, in __call__
app_1  |         await responder(scope, receive, send)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/gzip.py", line 44, in __call__
app_1  |         await self.app(scope, receive, self.send_with_gzip)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
app_1  |         raise exc
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
app_1  |         await self.app(scope, receive, sender)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
app_1  |         raise e
app_1  |       File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
app_1  |         await self.app(scope, receive, send)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
app_1  |         await route.handle(scope, receive, send)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
app_1  |         await self.app(scope, receive, send)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
app_1  |         response = await func(request)
app_1  |       File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 237, in app
app_1  |         raw_response = await run_endpoint_function(
app_1  |       File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
app_1  |         return await dependant.call(**values)
app_1  |       File "/workspace/stable-diffusion-webui/extensions/sd-webui-reactor/scripts/reactor_api.py", line 95, in reactor_image
app_1  |         return {"image": api.encode_pil_to_base64(result)}
app_1  |       File "/workspace/stable-diffusion-webui/modules/api/api.py", line 110, in encode_pil_to_base64
app_1  |         for key, value in image.info.items():
app_1  |     AttributeError: 'tuple' object has no attribute 'info'
app_1  | 
app_1  | ---

```
```


### Additional information

_No response_

**Comment by Gourieff** [comment]
Confirmed!
I will take a look!

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/sd-webui-reactor/commit/53f4b3d677c4e4cc7e4247466126b4e19fdb7738
Thanks for spotting!
